databases:
  - name: mqtt_dashboard
    databaseName: mqtt_dashboard_db
    user: collo

services:
  - type: web
    name: ist_project
    env: python
    buildCommand: "./build.sh"
    startCommand: "python manage.py runserver"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4