# Generated by Django 4.1.5 on 2023-01-31 15:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=256)),
                ('host', models.CharField(max_length=64)),
                ('port', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('connected', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2023, 1, 31, 18, 2, 49, 861920))),
                ('db_name', models.CharField(max_length=64)),
            ],
            options={
                'permissions': (('is_owner', 'Has all permissions'), ('can_add', 'Can create new project'), ('can_delete', 'Can delete project'), ('can_view', 'View only permission')),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=256)),
                ('path', models.CharField(default='/', max_length=64)),
                ('sub', models.BooleanField(default=True)),
                ('pub', models.BooleanField(default=False)),
                ('qos', models.IntegerField(choices=[(0, '0 (At Most Once)'), (1, '1 (At Least Once)'), (2, '2 (Exactly Once)')], default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=256)),
                ('format', models.CharField(choices=[('JSON', 'JSON'), ('SINGL', 'Single Variable')], max_length=5)),
                ('data_type', models.CharField(choices=[('NUM', 'Number'), ('STR', 'String'), ('LOC', 'Location'), ('BOOL', 'Boolean')], max_length=5)),
                ('path', models.CharField(blank=True, max_length=64, null=True)),
                ('key', models.CharField(blank=True, max_length=32, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
