# Generated by Django 4.1.6 on 2023-02-06 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dataobject_widget_type_alter_project_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataobject',
            name='widget_type',
            field=models.CharField(choices=[('SCATTER', 'Scatter Plot'), ('LINE', 'Line plot'), ('STATUS', 'Status Indicator'), ('MAP', 'Map')], default='LINE', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 4, 46, 8, 545649)),
        ),
    ]
